イベント開催会場を「株式会社インプレス」に更新
FutureReady-Kai/ichiyasaGitSample pull request #1
Opened 2024-04-25 08:02 UTC by FutureReady-Kai

###変更内容
イベント開催会場を「株式会社インプレス」に更新しました。

###背景
「株式会社インプレス」さんがイベント会場を提供してくださることになりました。

2024-04-25 08:59 UTC, imacoco-gf721 commented
修正ありがとうございます。
問題ありません。
マージをお願いします／マージします。

2024-04-25 09:02 UTC, imacoco-gf721 commented
LGTM（Look　Good 　To　Me）です。

2024-04-26 02:19 UTC, imacoco-gf721 requested changes
疑問点が3点あります。ご回答をお願いします。

2024-04-26 02:19 UTC, imacoco-gf721 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
LGMT

2024-04-26 02:19 UTC, imacoco-gf721 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
追加のコメントです

2024-04-26 02:53 UTC, FutureReady-Kai commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
ご指摘の部分の修正を終えました。
修正済みコ‐ドをプッシュしましたので、再度ご確認をお願いします。

2024-04-26 07:37 UTC, imacoco-gf721 approved these changes

2024-04-26 09:23 UTC, merged